/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cjava.view;

import cjava.controller.CategoriaBLL;
import cjava.entity.CategoriaDTO;
import cjava.entity.ProveedorDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edith
 */
public class categoriastodoview extends javax.swing.JInternalFrame {

    /**
     * Creates new form categoriastodoview
     */
    public categoriastodoview() {
        initComponents();
        
        listaCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tblCategorias);

        jLabel1.setText("Total de Categorías");

        lblTotal.setText("0");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(lblTotal)
                        .addGap(337, 337, 337)
                        .addComponent(btnCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
  this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCategorias;
    // End of variables declaration//GEN-END:variables

private void listaCategorias()
    {
    
        try {
            //se instancia el Objeto
            CategoriaBLL obj= new CategoriaBLL();
            
            List<CategoriaDTO> lista = obj.CategoriaListar(); //devuelve la lista de productos de la collections
            int nfilas=0;
            if (lista!=null && !lista.isEmpty()) {
                
                nfilas=lista.size();
                //se determina cuantas filas hay en la collection
                lblTotal.setText(nfilas + "");
                verCategoria(lista);
                
            }
            
        } catch (Exception e) {
        }
        
    }
        public void verCategoria(List<CategoriaDTO> lista)
                {
                DefaultTableModel tabla = (DefaultTableModel) tblCategorias.getModel(); //devuelv eel modelo de la tabla
                tabla.setRowCount(0);//limpiar la tabla
                
                //FOR PARA MANEJO DE COLLECIONES
                    for (CategoriaDTO p : lista) {
                        Object  []  datos= {p.getIdcategoria(),p.getNombre(), p.getdescripcion(),
                        p.getClass()};
                        
                        //se le asigna a un arreglo de tipo OBJETOS
                        tabla.addRow(datos);
                     
                    }                     
                        
               }
}





