/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cjava.view;

import cjava.controller.ClienteBLL;
import cjava.entity.ClienteDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class clientesTodoView_ extends javax.swing.JInternalFrame {

    /**
     * Creates new form clientesTodoView_
     */
    public clientesTodoView_() {
      initComponents();
        listaclientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblTotals = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setTitle("CLIENTES TODOS");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID CLIENTE", "NOMBRE", "DIRECCION", "RUCDNI", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        lblTotals.setText("Total de Clientes");

        lblTotal.setText("0");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTotals)
                        .addGap(26, 26, 26)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotals)
                    .addComponent(lblTotal)
                    .addComponent(btnCerrar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
   this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotals;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
 public void listaclientes() {

        try {
            ClienteBLL obj = new ClienteBLL();
            List<ClienteDTO> lista = obj.ClienteListar();
            int nfilas = 0;
            if (lista != null && !lista.isEmpty()) {
                nfilas = lista.size();
                lblTotal.setText(nfilas + " ");
                verCliente(lista);
            }

        } catch (Exception e) {
        }

    }

    public void verCliente(List<ClienteDTO> lista) {

        DefaultTableModel tabla = (DefaultTableModel) tblClientes.getModel();
        tabla.setRowCount(0);
        for (ClienteDTO c : lista) {

            Object[] datos = {c.getIdCLiente(), c.getNombre(), c.getDirección(), c.getRucDni(), c.getTelefono()};
            tabla.addRow(datos);
        }

    }

}

