/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cjava.view;

import cjava.controller.EmpleadoBLL;
import cjava.entity.EmpleadoDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edith
 */
public class empleadosTodoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form empleadosTodoView
     */
    public empleadosTodoView() {
        initComponents();
        listaempleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setTitle("LISTADO DE EMPLEADOS");

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID EMPLEADO", "APELLIDOS", "NOMBRE", "EMAIL", "USUARIO", "CLAVE"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        lblTotal.setText("0");

        jLabel1.setText("Total de Empleados");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(70, 70, 70)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(jLabel1)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblEmpleados;
    // End of variables declaration//GEN-END:variables

    private void listaempleados() {

        try {
            EmpleadoBLL obj = new EmpleadoBLL();
            List<EmpleadoDTO> lista = obj.EmpleadoListar();
            int nfilas = 0;
            if (lista != null && !lista.isEmpty()) {
                nfilas = lista.size();
                lblTotal.setText(nfilas + " ");
                verCliente(lista);
            }

        } catch (Exception e) {
        }
    }

    private void verCliente(List<EmpleadoDTO> lista) {

        DefaultTableModel tabla = (DefaultTableModel) tblEmpleados.getModel();
        tabla.setRowCount(0);
        for (EmpleadoDTO c : lista) {

            Object[] datos = {c.getIdempleado(), c.getApellido(), c.getNombres(), c.getEmail(), c.getUsuario(),c.getClave()};
            tabla.addRow(datos);
        }
    }
}
